name: hrsystem
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.7.0

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  page_transition: ^2.0.9
  salomon_bottom_bar: ^3.3.2
  convex_bottom_bar: ^3.2.0
  flutter_map: ^6.2.1
  latlong2: ^0.9.1
  geolocator: ^14.0.1
  camera: ^0.11.0
  image_picker: ^1.0.7

  flutter:
    sdk: flutter
  blur: ^3.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_lints: ^5.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo_launcher.png"

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/background.png
    - assets/images/team1.png
    - assets/images/team2.png
    - assets/images/team3.png
    - assets/images/team4.png
    - assets/images/team5.png
    - assets/images/team6.png
    - assets/images/photo_profile.png
    - assets/images/home_banner.png
    - assets/images/attendant_banner.png
    - assets/images/onboard1.png
    - assets/images/onboard2.png
    - assets/images/onboard3.png
    - assets/images/onboardFinal.png
    - assets/images/getstartedbg.png
    - assets/icons/email.png
    - assets/icons/employee.png
    - assets/icons/eye_closed.png
    - assets/icons/eye_open.png
    - assets/icons/password.png
    - assets/icons/phone.png
    - assets/icons/uncheck.png
    - assets/icons/checked.png
    - assets/icons/home_active.png
    - assets/icons/home_inactive.png
    - assets/icons/attendant_active.png
    - assets/icons/attendant_inactive.png
    - assets/icons/task_active.png
    - assets/icons/task_inactive.png
    - assets/icons/expense_active.png
    - assets/icons/expense_inactive.png
    - assets/icons/leave_active.png
    - assets/icons/leave_inactive.png
    - assets/icons/badge.png
    - assets/icons/notification.png
    - assets/icons/chat.png
    - assets/icons/meeting.png
    - assets/icons/task.png
    - assets/icons/clock.png
    - assets/icons/time_progress.png
    - assets/icons/message_card.png
    - assets/icons/calendar.png
    - assets/icons/calendar_card.png
    - assets/icons/flying_clock.png
    - assets/icons/pin.png
    - assets/icons/back.png
    - assets/icons/office.png
    - assets/icons/user.png
    - assets/icons/cctv.png
    - assets/icons/flag.png
    - assets/icons/my_location.png
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
      - family: Roboto
        fonts:
          - asset: assets/fonts/Roboto-Thin.ttf
            weight: 100
          - asset: assets/fonts/Roboto-Light.ttf
            weight: 300
          - asset: assets/fonts/Roboto-Regular.ttf
            weight: 400
          - asset: assets/fonts/Roboto-Medium.ttf
            weight: 500
          - asset: assets/fonts/Roboto-SemiBold.ttf
            weight: 600
          - asset: assets/fonts/Roboto-Bold.ttf
            weight: 700
          - asset: assets/fonts/Roboto-Black.ttf
            weight: 900
        # Italic variants (opsional)
          - asset: assets/fonts/Roboto-ThinItalic.ttf
            weight: 100
            style: italic
          - asset: assets/fonts/Roboto-LightItalic.ttf
            weight: 300
            style: italic
          - asset: assets/fonts/Roboto-Italic.ttf
            weight: 400
            style: italic
          - asset: assets/fonts/Roboto-MediumItalic.ttf
            weight: 500
            style: italic
          - asset: assets/fonts/Roboto-SemiBoldItalic.ttf
            weight: 600
            style: italic
          - asset: assets/fonts/Roboto-BoldItalic.ttf
            weight: 700
            style: italic
          - asset: assets/fonts/Roboto-BlackItalic.ttf
            weight: 900
            style: italic
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
